- name: Install yay using makepkg if it isn't installed already
  kewlfft.aur.aur:
    name: yay
    use: makepkg
    state: present
  become: yes
  become_user: aur_builder


- name: install package
  kewlfft.aur.aur:
    name: "{{ item }}"
    state: present
  with_items:
    - rsync
    - tar
    - zip
    - unzip
    - podman
  become: yes
  become_user: aur_builder
