- name: install postgresql
  kewlfft.aur.aur:
    name: "{{ item }}"
    state: present
  with_items:
    - postgresql
    - python-psycopg2
  become: yes
  become_user: aur_builder

- name: "Find out if PostgreSQL is initialized"
  ansible.builtin.stat:
    path: "/var/lib/postgres/data/pg_hba.conf"
  register: postgres_data
  become: yes

- name: "Initialize PostgreSQL"
  shell: "initdb --locale=C.UTF-8 --encoding=UTF8 -D /var/lib/postgres/data --data-checksums"
  when: not postgres_data.stat.exists
  become_user: postgres
  become: yes

- name: Start and enable postgresql service
  systemd:
    name: postgresql.service
    enabled: true
    state: started
  become: yes
