- name: install pi.hole packages
  kewlfft.aur.aur:
    name: "{{ item }}"
    state: present
  with_items:
    - pi-hole-core
  become: yes
  become_user: aur_builder

- name: update hosts file
  lineinfile:
    dest: /etc/hosts
    line: "{{ item }}"
    state: present
  loop:
    - "127.0.0.1 localhost"
    - "192.168.1.2 pi.hole {{ infra_server_hostname }}"
  become: yes

- name: copy openshift dns-masq configuration
  synchronize:
    src: ./etc/dnsmasq.d/00-openshift.conf
    dest: /etc/dnsmasq.d/00-openshift.conf
    rsync_opts:
    - "--chown=root:root"
  become: yes

- name: copy sso dns-masq configuration
  synchronize:
    src: ./etc/dnsmasq.d/00-sso.conf
    dest: /etc/dnsmasq.d/00-sso.conf
    rsync_opts:
    - "--chown=root:root"
  become: yes

- name: copy ocplab dns-masq configuration
  synchronize:
    src: ./etc/dnsmasq.d/00-ocplab.conf
    dest: /etc/dnsmasq.d/00-ocplab.conf
    rsync_opts:
    - "--chown=root:root"
  become: yes

- name: copy uptime dns-masq configuration
  synchronize:
    src: ./etc/dnsmasq.d/00-uptime.conf
    dest: /etc/dnsmasq.d/00-uptime.conf
    rsync_opts:
    - "--chown=root:root"
  become: yes

- name: Copy pihole.toml
  synchronize:
    src: ./etc/pihole/pihole.toml
    dest: /etc/pihole/pihole.toml
    rsync_opts:
    - "--chown=root:root"
  become: yes

- name: Start pi-hole
  systemd:
    name: pihole-FTL.service
    state: started
  become: yes
